// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqO_DIVUF1THo75c4BjCzFsDBReKCgFyc',
    appId: '1:533991987905:web:6047f0d189faefcb531240',
    messagingSenderId: '533991987905',
    projectId: 'resume-b3019',
    authDomain: 'resume-b3019.firebaseapp.com',
    storageBucket: 'resume-b3019.appspot.com',
    measurementId: 'G-5KRJLW3Y2P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOOKH5LVB0EnAdtou2W999Jq7pXuirp1w',
    appId: '1:533991987905:android:7683811acbbbbdf3531240',
    messagingSenderId: '533991987905',
    projectId: 'resume-b3019',
    storageBucket: 'resume-b3019.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA52Hs6kxKnqwMIinqck1qSr9e3tQ7QxU0',
    appId: '1:533991987905:ios:35469b9447ff134b531240',
    messagingSenderId: '533991987905',
    projectId: 'resume-b3019',
    storageBucket: 'resume-b3019.appspot.com',
    iosClientId: '533991987905-ukbg3btargli7e9c2m1b39bmf10botli.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA52Hs6kxKnqwMIinqck1qSr9e3tQ7QxU0',
    appId: '1:533991987905:ios:35469b9447ff134b531240',
    messagingSenderId: '533991987905',
    projectId: 'resume-b3019',
    storageBucket: 'resume-b3019.appspot.com',
    iosClientId: '533991987905-ukbg3btargli7e9c2m1b39bmf10botli.apps.googleusercontent.com',
    iosBundleId: 'com.example.resumeApp',
  );
}
